### ISSUE TITLE
pyinstaller with pywinio

### ISSUE THREAD

**Issue by chinarui-na** [starofrainnight/rabird.winio#20]
* pywinio version: 0.3.1
* Python version: 3.10.5
* Operating System: Windows 10

### Description
I used PyInstaller to package the PyWinio program as an executable script, which worked fine on my development machine but had problems on another machine

### What I Did

```
Traceback (most recent call last):
  File "winio.py", line 83, in <module>
  File "winio.py", line 43, in key_down
  File "winio.py", line 23, in get_winio
  File "pywinio\pywinio.py", line 133, in __init__
  File "pywinio\pywinio.py", line 400, in __initialize
  File "pywinio\pywinio.py", line 326, in install_driver
pywintypes.error: (1072, 'CreateService', '指定的服务已标记为删除。')
Traceback (most recent call last):
  File "winio.py", line 77, in <module>
  File "winio.py", line 43, in key_down
  File "winio.py", line 23, in get_winio
  File "pywinio\pywinio.py", line 133, in __init__
  File "pywinio\pywinio.py", line 401, in __initialize
  File "pywinio\pywinio.py", line 352, in __start_driver
pywintypes.error: (577, 'StartService', 'Windows 无法验证此文件的数字签名。某软件或硬件最近有所更改，可能安装了签名错误或损毁的文件，或者安装的文件可能是来路不明的恶意软件。')


```
Please modify the suffix from gif to exe
![gtsi](https://user-images.githubusercontent.com/55582739/193442769-fc462051-9e1d-4fd5-b2a9-fb4030a9a343.gif)

**Comment by starofrainnight** [comment]
Reference to README.rst this section: Driver Signing Requirements on 64-bit Systems

'The bundled copy of WinIo64.sys is signed with a self-signed certificate and can only be used on development/test machines with Windows running in a special "test" mode'

**Comment by BinchaoPeng** [comment]
how to use a signed winIo64.sys. I want to use it in normal mode.
I have a signed winIo64.sys, and I replace the original file in win32Binary floder.
but the error is also exist.
